// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package de.bht.se2.ideafactory.builder;

import de.bht.se2.ideafactory.model.IPortalUser;
import de.bht.se2.ideafactory.model.Idea;

public class IdeaBuilder extends IdeaBuilderBase<IdeaBuilder> {
	public static IdeaBuilder idea() {
		return new IdeaBuilder();
	}

	public IdeaBuilder() {
		super(new Idea());
	}

	public Idea build() {
		return getInstance();
	}
}

class IdeaBuilderBase<GeneratorT extends IdeaBuilderBase<GeneratorT>> {
	private Idea instance;

	protected IdeaBuilderBase(Idea aInstance) {
		instance = aInstance;
	}

	protected Idea getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT creator(IPortalUser aValue) {
		instance.setCreator(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT name(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT shortDecription(String aValue) {
		instance.setShortDecription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT detailedDescription(String aValue) {
		instance.setDetailedDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT specifications(String aValue) {
		instance.setSpecifications(aValue);

		return (GeneratorT) this;
	}
}
